# Клавиатуры (инлайн и reply) для бота
# Экспортируем все клавиатуры для удобного импорта

from bot.keyboards.reply import get_main_reply_keyboard

from bot.keyboards.inline import (
    get_language_level_keyboard,
    get_tariff_keyboard,
    get_payment_link_keyboard,
    get_after_payment_keyboard,
    get_welcome_keyboard,
    get_subscription_manage_keyboard,
    get_admin_panel_keyboard,
    get_add_user_duration_keyboard,
    get_stats_detail_keyboard,
    get_broadcast_segment_keyboard,
    get_broadcast_confirm_keyboard,
    get_broadcast_menu_keyboard,
    get_scheduled_segment_keyboard,
    get_rsvp_choice_keyboard,
    get_scheduled_confirm_keyboard,
    get_zoom_link_keyboard,
    get_rsvp_buttons_keyboard,
    get_rsvp_only_decline_keyboard,
    get_rsvp_only_attend_keyboard,
    get_calendar_keyboard,
    get_broadcast_history_back_keyboard,
    get_inactive_participants_keyboard,
    get_main_menu_keyboard,
    get_schedule_keyboard,
    get_starts1_schedule_keyboard,
    get_group_join_check_keyboard,
    get_event_navigation_keyboard,
    get_starts1_state_keyboard,
    get_starts1_cta_keyboard,
)

__all__ = [
    "get_language_level_keyboard",
    "get_tariff_keyboard",
    "get_payment_link_keyboard",
    "get_after_payment_keyboard",
    "get_welcome_keyboard",
    "get_subscription_manage_keyboard",
    "get_admin_panel_keyboard",
    "get_add_user_duration_keyboard",
    "get_stats_detail_keyboard",
    "get_broadcast_segment_keyboard",
    "get_broadcast_confirm_keyboard",
    "get_broadcast_menu_keyboard",
    "get_scheduled_segment_keyboard",
    "get_rsvp_choice_keyboard",
    "get_scheduled_confirm_keyboard",
    "get_zoom_link_keyboard",
    "get_rsvp_buttons_keyboard",
    "get_rsvp_only_decline_keyboard",
    "get_rsvp_only_attend_keyboard",
    "get_calendar_keyboard",
    "get_broadcast_history_back_keyboard",
    "get_inactive_participants_keyboard",
    "get_main_menu_keyboard",
    "get_schedule_keyboard",
    "get_starts1_schedule_keyboard",
    "get_main_reply_keyboard",
    "get_group_join_check_keyboard",
    "get_event_navigation_keyboard",
    "get_starts1_state_keyboard",
    "get_starts1_cta_keyboard",
]
